### ISSUE TITLE
Some data missing across OB issues

### ISSUE THREAD

**Issue by ronaldtse** [ituob/itu-ob-data#22] opened 2019-07-11 01:53 UTC
* "Lists annexed to the ITU Operational Bulletin"
* "Approval of ITU-T Recommendations”

Are both incomplete as we are finding ways to better model them.

**Comment by strogonoff** [comment] 2019-07-16 08:18
I don’t see obvious issues with the existing model. The migration is pending. First item is a duplicate of #21, and for second item I created https://github.com/ituob/ituob.org/issues/13.

**Closed by strogonoff** 2019-07-16 08:18 UTC
